=== keepwork/worker/worker-manage/src/main/webapp/WEB-INF/tld/sinoframe-config.dtd
<!-- 
 * 名称：Sinoframe MVC XML定义 
 * 创建: 2012/11/14<br />
 * 作者:<a herf="mailto:zhouzhiming@sinovatech.com">周志明</a>
-->
<!ELEMENT sinoframe-config (encode-setting?,mvcframe-config*,interseptors*) >
<!ELEMENT encode-setting (encode-rule+) >
<!ELEMENT encode-setting (encoding,url-pattern) >
<!ELEMENT encoding (#PCDATA) >
<!ELEMENT mvcframe-config (frame-name,frame-class,init-params) >
<!ELEMENT frame-name (#PCDATA) >
<!ELEMENT frame-class (#PCDATA) >
<!ELEMENT init-params (init-param*) >
<!ELEMENT init-param (param-name,param-value) >
<!ELEMENT param-name (#PCDATA) >
<!ELEMENT param-value (#PCDATA) >
<!ELEMENT interseptors (interseptor*) >
<!ELEMENT interseptor (interseptor-name,interseptor-class,interseptor-type,init-params,interseptor-mapping?) >
<!ELEMENT interseptor-name (#PCDATA) >
<!ELEMENT interseptor-class (#PCDATA) >
<!ELEMENT interseptor-type (#PCDATA) >
<!ELEMENT interseptor-mapping (url-pattern) >
<!ELEMENT url-pattern (#PCDATA) >

=== keepwork/worker/worker-wechat/src/main/webapp/WEB-INF/sinoframe-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sinoframe-config SYSTEM "tld/sinoframe-config.dtd">
<sinoframe-config>
<!--  
	<interseptors>
		<interseptor>
			<interseptor-name>BmsClientIntegrateIntersepter</interseptor-name>
			<interseptor-class>
				com.sinovatech.framework.web.interseptor.login.BmsClientIntegrateIntersepter</interseptor-class>
			<interseptor-type>PRE</interseptor-type>
			<interseptor-mapping>
				<url-pattern>*.jsp</url-pattern>
			</interseptor-mapping>
			<interseptor-mapping>
				<url-pattern>*.do</url-pattern>
			</interseptor-mapping>
		</interseptor>
	</interseptors>
-->
	<mvcframe-config>
		<frame-name>struts1</frame-name>
		<frame-class>
			com.sinovatech.framework.integrator.struts1.Struts1ActionServlet
		</frame-class>
		<init-params>
			<init-param>
				<!-- 和struts1配置类似 -->
				<param-name>config</param-name>
				<!-- 示例 /WEB-INF/struts1-cfg/struts-config.xml,/WEB-INF/struts1-cfg/test/struts-config-marketplat-extprop.xml-->
				<param-value>
					/WEB-INF/struts-cfg/struts-config.xml,
					/WEB-INF/struts-cfg/struts-config-sys.xml,
					/WEB-INF/struts-cfg/struts-config-domain.xml,
					/WEB-INF/struts-cfg/struts-config-pub.xml,
					/WEB-INF/struts-cfg/struts-config-shop.xml
				</param-value>
			</init-param>
		</init-params>
	</mvcframe-config>
</sinoframe-config>
